[project]
name = "minigit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thex810guy", email = "116834436+thex810guy@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pathlib>=1.0.1",
    "typer>=0.27.2",
]

[project.scripts]
minigit = "minigit.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
